#!/usr/bin/bash

if [ -f ~/.bash/functions/* ]; then
  for file in ~/.bash/functions/*; do
    source $file
  done
fi

source ~/.bash/aliases

source ~/.bash/completions/git
complete -o default -o nospace -F _git_checkout gco
complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_commit gc
complete -o default -o nospace -F _git_diff gd
complete -o default -o nospace -F _git_diff gdc
complete -o default -o nospace -F _git_diff gdcs
source ~/.bash/completions/subversion
source ~/.bash/completions/mategem
source ~/.bash/completions/bundler
complete -C ~/.bash/completions/rake -o default rake
complete -C ~/.bash/completions/project -o default c
complete -C ~/.bash/completions/project -o default cm
complete -C ~/.bash/completions/capistrano -o default cap

source $(brew --prefix nvm)/nvm.sh

# prompt: [ root ~ master +? ] % cmd
_user_root() { [ $USER == "root" ] && printf 'root '; }
_rvm_prompt() { local s=$(rvm-prompt v g); printf "${s:+ ${s}}"; }
export PS1="\[\e[0;35m\]\u\[\e[33m\]@\[\e[36m\]\h \$(_user_root)\[\e[33m\]\w\e[31m\]\$(__git_ps1)\[\e[36m\]\$(_rvm_prompt)\n\[\e[33m\]\[\e[32;1m\]$\[\e[0m\] "

export PATH=$HOME/bin:$HOME/.gem/ruby/1.8/bin:/opt/local/bin:/opt/local/sbin:/sw/bin:/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/mysql/bin
export PATH=/Users/duksis/Library/Haskell/bin:$PATH
export PATH=$HOME/.exenv/bin:$PATH

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export EDITOR="vim"
export SVN_EDITOR=$EDITOR
export LC_CTYPE=UTF-8
export LANG=en_US.UTF-8

eval "$(exenv init -)"

### Bash http://blog.macromates.com/2008/working-with-history-in-bash/
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

### COLORS
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

### Oracle

### MySql
