#!/usr/bin/bash

if [ -d ~/.bash/functions ]; then
  for file in ~/.bash/functions/*; do
    source $file
  done
fi

source ~/.bash/aliases

source ~/.bash/completions/git
source ~/.bash/completions/bundler
complete -C ~/.bash/completions/rake -o default rake
complete -C ~/.bash/completions/project -o default c

# prompt: [ root ~ master +? ] % cmd
_user_root() { [ $USER == "root" ] && printf 'root '; }
export PS1="\[\e[0;35m\]\u\[\e[33m\]@\[\e[36m\]\h \$(_user_root)\[\e[33m\]\w\e[31m\]\$(__git_ps1)\[\e[36m\]\n\[\e[33m\]\[\e[32;1m\]$\[\e[0m\] "

export PATH=$HOME/bin:$HOME/.asdf/shims:/opt/local/bin:/opt/local/sbin:/sw/bin:/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/mysql/bin
export PATH=/Users/duksis/Library/Haskell/bin:~/.cabal/bin:$PATH
export PATH=$PATH:$HOME/bin

### Rust the stuff
export PATH=$PATH:$HOME/.cargo/bin

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export EDITOR="vim"
export SVN_EDITOR=$EDITOR
export LC_CTYPE=UTF-8
export LANG=en_US.UTF-8

### Bash http://blog.macromates.com/2008/working-with-history-in-bash/
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

### COLORS
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

### Redis
export REDIS_PATH=/usr/local/bin/redis-server

### bash
export PROMPT_COMMAND='history -a' # makes bash to update history before each promt
